server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://10.19.33.16:18989/snaker?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: asiainfo#12345
    driver-class-name: com.mysql.jdbc.Driver